apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 4200
      nodePort: 31000
  type: NodePort
