version: "3.8"

services:
  frontend:
    # build:
    #   context: ./client
    #   dockerfile: ./Dockerfile
    image: fe
    ports:
      - "8080:8080"

    depends_on:
      - backend

  backend:
    image: be
    # build:
    #   context: ./server
    #   dockerfile: ./Dockerfile
    ports:
      - "5200:5200"
